Connect api
dvcorreia1984/bookstoreCMS pull request #4
Opened 2023-09-01 10:33 UTC by dvcorreia1984

In this pull request the following was done: 

- Implementation of Bookstore API
- Implementation of axios with createAsyncThunk to make your HTTP requests to the backend
- Fetching books from the Bookstore API
- Refactoring of Add and Remove functions

2023-09-01 11:25 UTC, shahadat3669 requested changes
Hi @dvcorreia1984 , 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ createAsyncThunk is imported in the project.
✅ All HTTP requests are made with `axios` .all HTTP requests are made with [axios](https://axios-http.com/docs/intro) .
✅ `useEffect` is used when dispatching the `fetchBooks` function in `<BookList>`


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 11:25 UTC, shahadat3669 commented on src/redux/books/booksSlice.js
> +  initialState: {},
- [ ] You've made significant progress with your book add and remove functionality, which is working smoothly. However, in the previous milestone, books were stored as an array of objects, with each book represented as an individual object. I understand that the API provides data in a different format. So rather than altering the way books are stored in the Redux store, I recommend adding functionality to transform the API output into an array of objects and then storing it in the Redux store, as you did in the previous milestone as per [project requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/connect_to_api_v2_1.md#:~:text=Your%20application%20should%20behave%20the%20same%20way%20after%20the%20refactoring).

Currently, your `books` are stored like this:

```javascript
books: {
  '128b6a4d-9dd7-4d6b-ab65-fd29fc7448de': [
    {
      author: 'Nameless Trichor',
      title: 'Whats my Name',
      category: 'Philosophy'
    }
  ],
  'eaf57c7b-083d-4728-a5e1-d53b6759fa30': [
    {
      author: 'new author',
      title: 'new book',
      category: ''
    }
  ]
}
```

To achieve the desired format, you'll need to add functionality to transform `books` into an array like this:

```javascript
books= [
  {
    item_id: '128b6a4d-9dd7-4d6b-ab65-fd29fc7448de',
    title: 'Whats my Name',
    author: 'Nameless Trichor',
    category: 'Philosophy',
  },
  {
    item_id: 'eaf57c7b-083d-4728-a5e1-d53b6759fa30',
    title: 'new book',
    author: 'new author',
    category: '',
  },
];
```

This approach will maintain consistency with your previous milestone and ensure compatibility with your Redux store structure. Keep up the great work, and thank you for your attention to maintaining a structured and organized data format! 🌟📚

2023-09-01 11:25 UTC, shahadat3669 commented on src/redux/books/booksSlice.js
>    },
You're doing a great job with your `addBook` method, which successfully adds a new book to the API using an Axios POST request. However, to align with the project's requirements, it's essential to add functionality that updates both the Redux store and the DOM immediately after a new book is added. Currently, the updates only become visible after a page refresh, which is not the expected behavior.

To address this, you can follow these steps:

- [ ] After successfully adding the book to the API, add functionality to update the Redux store with the new book information. This should be done right after receiving a successful response from the API.
- [ ] Add functionality to update the DOM with the newly added book

[BookstoreCMS.webm](https://github.com/dvcorreia1984/bookstoreCMS/assets/55840999/65f92e52-3746-4614-9228-b61e22145fee)

By implementing these, you will ensure that both the Redux store and the DOM display the updated book list without requiring a page refresh. This is crucial for providing a seamless user experience in accordance with the project requirements. Keep up the excellent work! 🌟📚

2023-09-01 11:25 UTC, shahadat3669 commented on src/redux/books/booksSlice.js
>    },
You've done a great job with your `removeBook` method, which successfully deletes a book by its ID. However, in alignment with the project requirements, it's crucial to ensure that, upon successful deletion, the book is removed not only from the API but also from the Redux store and the DOM. Currently, the book remains in the Redux store and the DOM even after deletion from the API.

To achieve this, you can follow these steps:

- [ ] After successfully deleting the book from the API, add functionality to remove the book from the Redux store.
- [ ] Add functionality to update the DOM immediately.

[BookstoreCMS (1).webm](https://github.com/dvcorreia1984/bookstoreCMS/assets/55840999/d5d98897-d4f3-428f-a3f2-d19871ca855f)


By implementing these changes, you'll ensure that both the Redux store and the DOM display the updated book list after a book is successfully deleted, as per the project requirements. This enhancement will provide a smoother user experience and maintain data consistency. Keep up the excellent work! 🌟🗑️

2023-09-01 11:25 UTC, shahadat3669 commented on src/components/BookList.js
> +          </div>
- [ ] Well! You're aware that each milestone is an opportunity to enhance your project and introduce new features. I noticed that in a previous milestone, there was a request to have a `Book` component responsible for individual book functionality, but it appears that this component has been removed, and book rendering is now handled within the `BookList` component. To align with the original request and maintain a more modular and organized codebase, I recommend reconsidering the `Book` component. Adding or undoing the `Book` component would be beneficial, as it would allow for better separation of concerns and code modularity. 

By having a dedicated `Book` component, you can handle the rendering and display of individual books more efficiently, which can contribute to cleaner and more maintainable code. It's important to maintain consistency with the project's previous requirements whenever possible. Keep up the great work, and thank you for your commitment to improving your project with each milestone! 🌟📖

2023-09-02 11:35 UTC, Johnadibe requested changes
# Status: Required Changes ♻️
### Hi @dvcorreia1984🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- Implemented some changes requested by the previous reviewer✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 11:35 UTC, Johnadibe commented on src/components/BookList.js
> +          </div>
> - [ ] Hi, I wanted to discuss a suggestion that was made by the previous code reviewer. In the last review, it was recommended to have a dedicated `Book` component for handling individual book functionality. However, it seems this recommendation wasn't implemented, and book rendering is still being handled within the `BookList` component.👍
> 
> I'd like to kindly request that you reconsider adding the `Book` component to your project. Having a dedicated 'Book' component allows for better separation of concerns. Each component can focus on its specific task, making the codebase more organized and easier to maintain.👍
> 
> Create a Book component:
```
const Book = ({ book, onRemove }) => {
  return (
    <div>
      <li>
        {book.title} by {book.author} ({book.category})
      </li>
      <div>
        <button type="button" onClick={() => onRemove(book.id)}>
          Remove
        </button>
      </div>
    </div>
  );
};
```

In BookList component:

```
<ul>
        {books.map((book) => (
          // Render individual books using the Book component
          <Book key={book.id} book={book} onRemove={handleRemoveBook} />
        ))}
      </ul>
```

2023-09-02 12:21 UTC, dvcorreia1984 commented on src/components/BookList.js
> +          </div>
Hi @Johnadibe, I agree. This will work much better. I added this component as requested.

2023-09-02 12:40 UTC, Alusp approved these changes
Hi @dvcorreia1984, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats](https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif)

## Highlights
✅ Used axios to make HTTP requests✔
✅ Rendered books inside of the BookList component✔
✅ Added extraReducers section of booksSlice where you actually updated the state✔
✅ AddBook and removeBook work the same as before ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 12:44 UTC, merged